In [58]:
# 0. 사용할 패키지 불러오기
from keras.utils import np_utils
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np
from numpy import argmax
import sys

In [59]:
# 1. 실무에 사용할 데이터 준비하기
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)

(60000, 28, 28)
(60000,)


In [60]:
#print(y_train[25])
#for x in x_train[25]:
 #   for i in x:
  #      sys.stdout.write('%d\t'%i)
   # sys.stdout.write('\n')

x_test 데이터 중 10000개를 784개 1차원 배열로 변환하되 255 로 나누어 0~1 사이로 정규화하는 루틴
np_utils.to_categorical(y_test, 10) 은 0~9 까지의 테스트 데이터를 원핫인코딩해주는 함수. 
아마도 10은 디폴트인가 봄.
np.random.choice 는 해당 행렬에서 5개 만큼 랜덤으로 선택해주는 함수

In [66]:
x_test = x_test.reshape(10000, 784).astype('float32') / 255.0
print(y_test[1])
y_test = np_utils.to_categorical(y_test)
print(y_test[1])
print(x_test.shape[0])
xhat_idx = np.random.choice(x_test.shape[0], 5)
# numpy.random.choice(a, size=None, replace=True, p=None)
# a : 배열이면 원래의 데이터, 정수이면 range(a) 명령으로 데이터 생성
# size : 정수. 샘플 숫자
# replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능
# p : 배열. 각 데이터가 선택될 수 있는 확률

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]
10000


In [62]:
print(xhat_idx)

[8935 2781 9767 4113 7830]


In [63]:
xhat = x_test[xhat_idx]

In [64]:
# 2. 모델 불러오기
from keras.models import load_model
model = load_model('mnist_mlp_model.h5')

# 3. 모델 사용하기
yhat = model.predict_classes(xhat)

print(yhat)
print(xhat_idx[0])
print(y_test[xhat_idx[0]])
print(argmax(y_test[xhat_idx[0]]))

[9 9 9 2 0]
8935
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
9


argmax 는 최고값이 있는 위치를 뜻함. 원핫인코딩인 것을 감안하면 숫자로 도출됨을 알 수 있음

In [65]:
for i in range(5):
    print('True : ' + str(argmax(y_test[xhat_idx[i]])) + ', Predict : ' + str(yhat[i]))

True : 9, Predict : 9
True : 9, Predict : 9
True : 9, Predict : 9
True : 2, Predict : 2
True : 0, Predict : 0
