In [1]:
# 0. 사용할 패키지 불러오기
from keras.utils import np_utils
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np
from numpy import argmax

Using TensorFlow backend.


In [13]:
# 1. 실무에 사용할 데이터 준비하기
# 랜덤시드 고정시키기
np.random.seed(5)
dataset = np.loadtxt("./pima-indians-diabetes2.csv", delimiter=",")
x_train = dataset[:700,0:8]
y_train = dataset[:700,8]
x_test = dataset[700:,0:8]
y_test = dataset[700:,8]

xhat_idx = np.random.choice(x_test.shape[0], 5)
print(xhat_idx)
xhat1 = x_test[61]
print(xhat1)
xhat = x_test[xhat_idx]
print(xhat)

[61 16  8 62 27]
[  9.    170.     74.     31.      0.     44.      0.403  43.   ]
[[9.00e+00 1.70e+02 7.40e+01 3.10e+01 0.00e+00 4.40e+01 4.03e-01 4.30e+01]
 [3.00e+00 1.73e+02 7.80e+01 3.90e+01 1.85e+02 3.38e+01 9.70e-01 3.10e+01]
 [9.00e+00 1.64e+02 7.80e+01 0.00e+00 0.00e+00 3.28e+01 1.48e-01 4.50e+01]
 [9.00e+00 8.90e+01 6.20e+01 0.00e+00 0.00e+00 2.25e+01 1.42e-01 3.30e+01]
 [0.00e+00 1.41e+02 8.40e+01 2.60e+01 0.00e+00 3.24e+01 4.33e-01 2.20e+01]]


In [16]:
# 2. 모델 불러오기
from keras.models import load_model
model = load_model('diabetesPred_mlp_model.h5')

# 3. 모델 사용하기
yhat = model.predict_classes(xhat)

for i in range(5):
    print('True : ' + str(y_test[xhat_idx[i]]) + ', Predict : ' + str(yhat[i]))

True : 1.0, Predict : [1]
True : 1.0, Predict : [1]
True : 1.0, Predict : [1]
True : 0.0, Predict : [0]
True : 0.0, Predict : [0]
